# Numpy

In [1]:
import numpy as np

## Creating Array

In [3]:
#array
x = np.array([1,2,3])
x

array([1, 2, 3])

In [9]:
#matrix 3x3
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
x.shape

(3, 3)

In [23]:
#array of range of values
y = np.arange(0,20,2)
y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
len(y)

10

In [25]:
y.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [26]:
#some useful matrix

#matrix of all ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
#matrix of all zeroes
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#diagonal matrix

z = np.diag([1,2,3])
z

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
#stack vertically

np.vstack((z,z**2))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [39]:
#stack horizontally

np.hstack((z,z**2))

array([[1, 0, 0, 1, 0, 0],
       [0, 2, 0, 0, 4, 0],
       [0, 0, 3, 0, 0, 9]])

## Operation

In [40]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

#element wise Addition
x+y

array([5, 7, 9])

In [42]:
#element wise Multiplication
x*y

array([ 4, 10, 18])

In [50]:
#Transpose of a matrix

matrix = np.arange(3,11)
matrix = matrix.reshape(2,4)
matrix

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [51]:
matrix.transpose()

array([[ 3,  7],
       [ 4,  8],
       [ 5,  9],
       [ 6, 10]])

In [52]:
#max, mean ...


r = np.array([9, 5, 4, 3, 2, 6])

r.sum()

29

In [59]:
r.max()

9

In [57]:
#index of maximum value
r.argmax()

0

In [56]:
r.min()

2

In [58]:
r.argmin()

4

In [54]:
r.mean()

4.833333333333333

In [55]:
r.std()

2.266911751455907

# Index Slicing

In [63]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [64]:
s[0], s[4]

(0, 16)

In [66]:
# 0 1 2 3
#index position

s[:4]

array([0, 1, 4, 9])

In [69]:
#last for elements

s[-4:]

array([ 81, 100, 121, 144])

In [73]:
#matrix slicing

r = np.arange(36)
r = r.reshape(6, 6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
# 3rd row 3rd column

r[2,2]

14

In [81]:
#it has mainly to parts
#r[part1, part2]
#part 1 for row selection
#part 2for column selection


r[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
#select 3rd row and complete column
r[2,:]

array([12, 13, 14, 15, 16, 17])

In [84]:
#selct 3rd column and complete row
r[:,2]

array([ 2,  8, 14, 20, 26, 32])